version: "3.9"

services:
  ivi_pikabu:
    image: imsamurai/ivi
    deploy:
      replicas: 50
    restart: always
  sms_bomber:
    image: imsamurai/sms-bomber
    deploy:
      replicas: 0
    restart: always
    command: "'Ostanovite VOINU s UKRAINOI! Ne verte smi! Vyhodite na miting!'"
  callmeback:
    image: imsamurai/callmeback
    deploy:
      replicas: 0
    restart: always
  jerdesh:
    image: imsamurai/jerdesh
    deploy:
      replicas: 0
    restart: always
