version: "3.9"

services:
  tutu:
    image: imsamurai/ban
    deploy:
      replicas: 8
    restart: always
    command: "tutu-sentry ph_priority 100"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
#  apteka:
#    image: imsamurai/caller
#    deploy:
#      replicas: 4
#    restart: always
#    command: "apteka ph 100"
#    ulimits:
#      nofile:
#        soft: 140000
#        hard: 140000
#  polypay_priority:
#    image: imsamurai/caller
#    deploy:
#      replicas: 0
#    restart: always
#    command: "polypay ph 100"
#    ulimits:
#      nofile:
#        soft: 140000
#        hard: 140000
#  yabloko161_priority:
#    image: imsamurai/caller
#    deploy:
#      replicas: 0
#    restart: always
#    command: "yabloko161 ph 100"
#    ulimits:
#      nofile:
#        soft: 140000
#        hard: 140000
