version: "3.9"

services:
  autotown_priority:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "autotown ph_voenkomats"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  zonatelecom_priority:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "zonatelekom ph_voenkomats"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  webmoika_priority:
    image: imsamurai/caller
    deploy:
      replicas: 0
    restart: always
    command: "webmoika ph_voenkomats"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  coworkstation_priority:
    image: imsamurai/caller
    deploy:
      replicas: 0
    restart: always
    command: "coworkstation ph_voenkomats"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  netzaliva_priority:
    image: imsamurai/caller
    deploy:
      replicas: 0
    restart: always
    command: "netzaliva ph_voenkomats"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  yabloko161_priority:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "yabloko161 ph_voenkomats"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  polypay_priority:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "polypay ph_voenkomats"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
#  polypay_all:
#    image: imsamurai/caller
#    deploy:
#      replicas: 1
#    restart: always
#    command: "polypay ph 50"
#    ulimits:
#      nofile:
#        soft: 140000
#        hard: 140000
#  egks_all:
#    image: imsamurai/caller
#    deploy:
#      replicas: 1
#    restart: always
#    command: "egks ph 50"
#    ulimits:
#      nofile:
#        soft: 140000
#        hard: 140000
#  superbankrot_all:
#    image: imsamurai/superbankrot
#    deploy:
#      replicas: 1
#    restart: always
#    command: "ph 50"
#    ulimits:
#      nofile:
#        soft: 140000
#        hard: 140000
