version: "3.9"

services:
  ivi: #almost useless
    image: imsamurai/ivi
    deploy:
      replicas: 1
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  sms_bomber: #almost useless
    image: imsamurai/sms-bomber
    deploy:
      replicas: 1
    restart: always
    command: "'Ostanovite VOINU s UKRAINOI! Ne verte smi! Vyhodite na miting!'"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  callmeback: #died
    image: imsamurai/callmeback
    deploy:
      replicas: 0
    restart: always
  jerdesh: #almost useless
    image: imsamurai/jerdesh
    deploy:
      replicas: 0
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  letu: #died
    image: imsamurai/letu
    deploy:
      replicas: 0
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  celfin: #died
    image: imsamurai/celfin
    deploy:
      replicas: 0
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
