version: "3.9"

services:
  findclone:
    image: imsamurai/findclone
    deploy:
      replicas: 1
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  kruassanfamily:
    image: imsamurai/kruassanfamily
    deploy:
      replicas: 1
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  chibbis:
    image: imsamurai/chibbis
    deploy:
      replicas: 1
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  nskavtovokzal:
    image: imsamurai/nskavtovokzal
    deploy:
      replicas: 1
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  avtoinline:
    image: imsamurai/avtoinline
    deploy:
      replicas: 1
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  sushilandia:
    image: imsamurai/sushilandia
    deploy:
      replicas: 1
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
