version: "3.9"

services:
  netzaliva_priority:
    image: imsamurai/netzaliva
    deploy:
      replicas: 1
    restart: always
    command: "netzaliva ph_priority 50"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  netzaliva_all:
    image: imsamurai/netzaliva
    deploy:
      replicas: 1
    restart: always
    command: "netzaliva ph 100"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  yabloko161_priority:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "yabloko161 ph_priority 50"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  yabloko161_all:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "yabloko161 ph 100"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  polypay_all:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "polypay ph 100"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  egks_all:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "egks ph 100"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  superbankrot_all:
    image: imsamurai/superbankrot
    deploy:
      replicas: 1
    restart: always
    command: "ph 100"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
