version: "3.9"

services:
  apteka:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "apteka ph 100"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  polypay_priority:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "polypay ph_voenkomats"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  yabloko161_priority:
    image: imsamurai/caller
    deploy:
      replicas: 1
    restart: always
    command: "yabloko161 ph_voenkomats"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
