version: "3.9"

services:
  ivi:
    image: imsamurai/ivi
    deploy:
      replicas: 2
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  sms_bomber:
    image: imsamurai/sms-bomber
    deploy:
      replicas: 2
    restart: always
    command: "'Ostanovite VOINU s UKRAINOI! Ne verte smi! Vyhodite na miting!'"
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  callmeback: #died
    image: imsamurai/callmeback
    deploy:
      replicas: 0
    restart: always
  jerdesh:
    image: imsamurai/jerdesh
    deploy:
      replicas: 2
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
  letu:
    image: imsamurai/letu
    deploy:
      replicas: 4
    restart: always
    ulimits:
      nofile:
        soft: 140000
        hard: 140000
